### ISSUE TITLE
Unable to install a requirement which I suppose is opencv-python-headless

### ISSUE THREAD

**Issue by edisan27** [leblancfg/autocrop#182]
Hello, I'm trying to install autocrop and have installed Pip 23.1.2 and Python 3.9.10 but keeps getting this error while install opencv-python-headless, been trying to install opencv-python also but got the same error, been wondering if there's a way to solve this?
I'm using Windows 10 64-bit by the way
Thanks

pip install autocrop
Collecting autocrop
  Using cached autocrop-1.3.0-py3-none-any.whl (158 kB)
Requirement already satisfied: numpy>=1.10 in c:\program files\inkscape\lib\python3.9\site-packages (from autocrop) (1.21.5)
Collecting opencv-python-headless<5,>=3 (from autocrop)
  Using cached opencv-python-headless-4.7.0.72.tar.gz (91.1 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and platform_system != "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
      Collecting setuptools==59.2.0
        Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
      Collecting wheel==0.37.0
        Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
      Collecting cmake>=3.1
        Using cached cmake-3.26.3.tar.gz (35 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting pip
        Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
      Collecting scikit-build>=0.13.2
        Using cached scikit_build-0.17.2-py3-none-any.whl (82 kB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        Getting requirements to build wheel did not run successfully.
        exit code: 1

        [40 lines of output]
        Traceback (most recent call last):
          File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
            backend = _build_backend()
          File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
            obj = import_module(mod_path)
          File "C:\Program Files\Inkscape\lib\python3.9\importlib\__init__.py", line 127, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
          File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
          File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
          File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
          File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
          File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
          File "<frozen importlib._bootstrap_external>", line 850, in exec_module
          File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
          File "C:\Users\Edi\AppData\Local\Temp\pip-build-env-0qpuus94\overlay\lib\python3.9\site-packages\setuptools\__init__.py", line 253, in <module>
            monkey.patch_all()
          File "C:\Users\Edi\AppData\Local\Temp\pip-build-env-0qpuus94\overlay\lib\python3.9\site-packages\setuptools\monkey.py", line 101, in patch_all
            patch_for_msvc_specialized_compiler()
          File "C:\Users\Edi\AppData\Local\Temp\pip-build-env-0qpuus94\overlay\lib\python3.9\site-packages\setuptools\monkey.py", line 164, in patch_for_msvc_specialized_compiler
            patch_func(*msvc9('find_vcvarsall'))
          File "C:\Users\Edi\AppData\Local\Temp\pip-build-env-0qpuus94\overlay\lib\python3.9\site-packages\setuptools\monkey.py", line 151, in patch_params
            mod = import_module(mod_name)
          File "C:\Program Files\Inkscape\lib\python3.9\importlib\__init__.py", line 127, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
          File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
          File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
          File "<frozen importlib._bootstrap_external>", line 850, in exec_module
          File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
          File "C:\Users\Edi\AppData\Local\Temp\pip-build-env-0qpuus94\overlay\lib\python3.9\site-packages\setuptools\_distutils\msvc9compiler.py", line 295, in <module>
            raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
        distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\lib\python3.9\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Inkscape\lib\python3.9\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Inkscape\bin\pip.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\cli\main.py", line 79, in main
    return command.main(cmd_args)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\cli\base_command.py", line 101, in main
    return self._main(args)
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\cli\command_context.py", line 20, in main_context
    yield
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\utils\temp_dir.py", line 70, in tempdir_registry
    yield _tempdir_registry
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\utils\temp_dir.py", line 36, in global_tempdir_manager
    _tempdir_manager = old_tempdir_manager
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "C:\Program Files\Inkscape\lib\python3.9\contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\utils\temp_dir.py", line 156, in __exit__
    self.cleanup()
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
  File "C:\Program Files\Inkscape\lib\python3.9\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\Inkscape\lib\python3.9\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
  File "C:\Program Files\Inkscape\lib\python3.9\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "C:\Program Files\Inkscape\lib\python3.9\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Inkscape\lib\python3.9\shutil.py", line 622, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Inkscape\lib\python3.9\shutil.py", line 622, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Inkscape\lib\python3.9\shutil.py", line 622, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 7 more times]
  File "C:\Program Files\Inkscape\lib\python3.9\shutil.py", line 627, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Inkscape\lib\python3.9\shutil.py", line 625, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Edi\\AppData\\Local\\Temp\\pip-install-gpddmevc\\opencv-python-headless_530ba8bcdcf04e77a35567e9b34cb069\\opencv\\platforms\\android\\service\\engine\\src\\org\\opencv\\engine\\MarketConnector.java'

**Comment by leblancfg** [comment]
@edisan27 That looks like an issue with the pip installation. [This seemingly-related issue](https://github.com/pypa/pip/issues/7865) notes you be able to make it work by calling the pip module directly: 

```
python -m pip install autocrop
```
