### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tegk** [leblancfg/autocrop#32]
```
C:\Users\XXX\Desktop>autocrop -i j -o crop -w 600 -H 600
Processing images in folder: C:\Users\XXX\Desktop\X
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\autocrop.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\autocrop\autocrop.py", line 290, in cli
    main(args.input, args.output, args.height, args.width)
  File "c:\python27\lib\site-packages\autocrop\autocrop.py", line 139, in main
    shutil.copyfile(i, o)
  File "c:\python27\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\XXX\\Desktop\\Y\\JY.jpg'
```

Please implement error handling. Happens with many pictures.

**Comment by leblancfg** [comment]
Closing this for now. Feel free to re-open if you get back to it!
