### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ak9250** [leblancfg/autocrop#63]
I am getting this error
Processing images in folder: /path/to/folder/of/images/
Traceback (most recent call last):
  File "/usr/local/bin/autocrop", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/autocrop/autocrop.py", line 398, in cli
    args.padRight)
  File "/usr/local/lib/python3.6/dist-packages/autocrop/autocrop.py", line 216, in main
    padRight)
  File "/usr/local/lib/python3.6/dist-packages/autocrop/autocrop.py", line 113, in crop
    height, width = (image.shape[:2])
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by ak9250** [comment]
figured it out had to verify images
