### ISSUE TITLE
'Module' object is not callable

### ISSUE THREAD

**Issue by rakemen** [leblancfg/autocrop#98]
Can you suggest what this error could be installed via pip on Windows.

![image](https://user-images.githubusercontent.com/6099915/78147616-64c49800-7451-11ea-987e-b0851296e946.png)

**Comment by leblancfg** [comment]
Hi @rakemen , I'mgoing to need some more information for this. What were you doing? Can you check what version you are using? Thanks.

**Comment by hugovk** [comment]
I just got the same thing (macOS):

```console
$ python --version
Python 3.8.2
$ pip install autocrop
Collecting autocrop
  Using cached autocrop-1.0.0.tar.gz (158 kB)
Requirement already satisfied, skipping upgrade: numpy>=1.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from autocrop) (1.18.1)
Collecting opencv-python<4,>=3
  Downloading opencv_python-3.4.9.31-cp38-cp38-macosx_10_9_x86_64.whl (47.5 MB)
     |████████████████████████████████| 47.5 MB 22 kB/s
Requirement already satisfied, skipping upgrade: Pillow>5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Pillow-7.1.0-py3.8-macosx-10.9-x86_64.egg (from autocrop) (7.1.0)
Building wheels for collected packages: autocrop
  Building wheel for autocrop (setup.py) ... done
  Created wheel for autocrop: filename=autocrop-1.0.0-py3-none-any.whl size=157719 sha256=df2b89fcf103de7b9c3281bf860a8e2ec3399c8edad0e44b458118f942cd485b
  Stored in directory: /Users/hugo/Library/Caches/pip/wheels/0b/cc/62/9e2cc89cd77fba6732fc6e8113a393b70cd06ec19f282f3262
Successfully built autocrop
Installing collected packages: opencv-python, autocrop
Successfully installed autocrop-1.0.0 opencv-python-3.4.9.31
$ autocrop --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/autocrop", line 8, in <module>
    sys.exit(cli())
TypeError: 'module' object is not callable
$ autocrop --version
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/autocrop", line 8, in <module>
    sys.exit(cli())
TypeError: 'module' object is not callable
$ autocrop
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/autocrop", line 8, in <module>
    sys.exit(cli())
TypeError: 'module' object is not callable
```

**Comment by leblancfg** [comment]
Sorry about that. `setup.py` file needed to be pointed at the right direction after refactoring, and I don't have any post-install tests. :fearful: 

Fixed the problem and updated PyPI package to `1.0.1`. Please let me know if it works!

**Comment by hugovk** [comment]
Looking good now, thanks for the quick fix!

**Comment by rakemen** [comment]
Fixed. Thank you.
